//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace lab3Client.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("lab3Client.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DeWitt, Book Observer v0.5.
        /// </summary>
        public static string About0 {
            get {
                return ResourceManager.GetString("About0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Front-End: WPF; Back-End: C#;.
        /// </summary>
        public static string About1 {
            get {
                return ResourceManager.GetString("About1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1121,Popov Daniil.
        /// </summary>
        public static string About2 {
            get {
                return ResourceManager.GetString("About2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ITMO University.
        /// </summary>
        public static string About3 {
            get {
                return ResourceManager.GetString("About3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2015.
        /// </summary>
        public static string About4 {
            get {
                return ResourceManager.GetString("About4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About Program.
        /// </summary>
        public static string AboutTitle {
            get {
                return ResourceManager.GetString("AboutTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Book can&apos;t have empty fields!.
        /// </summary>
        public static string Add_ErrorInfo {
            get {
                return ResourceManager.GetString("Add_ErrorInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ISBN must be a 13-digit number.
        /// </summary>
        public static string Add_ErrorISBN {
            get {
                return ResourceManager.GetString("Add_ErrorISBN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please insert correct WriteTime (YYYY).
        /// </summary>
        public static string Add_ErrorWriteTime {
            get {
                return ResourceManager.GetString("Add_ErrorWriteTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Book.
        /// </summary>
        public static string Add_Title {
            get {
                return ResourceManager.GetString("Add_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string ButtonCancel {
            get {
                return ResourceManager.GetString("ButtonCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        public static string ButtonOK {
            get {
                return ResourceManager.GetString("ButtonOK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Books.
        /// </summary>
        public static string CountLabel {
            get {
                return ResourceManager.GetString("CountLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Host.
        /// </summary>
        public static string CS_Host {
            get {
                return ResourceManager.GetString("CS_Host", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Port.
        /// </summary>
        public static string CS_Port {
            get {
                return ResourceManager.GetString("CS_Port", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose a Server.
        /// </summary>
        public static string CS_Title {
            get {
                return ResourceManager.GetString("CS_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Author.
        /// </summary>
        public static string FieldAuthor {
            get {
                return ResourceManager.GetString("FieldAuthor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Genre.
        /// </summary>
        public static string FieldGenre {
            get {
                return ResourceManager.GetString("FieldGenre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ISBN.
        /// </summary>
        public static string FieldISBN {
            get {
                return ResourceManager.GetString("FieldISBN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string FieldName {
            get {
                return ResourceManager.GetString("FieldName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Synopsis.
        /// </summary>
        public static string FieldSynopsis {
            get {
                return ResourceManager.GetString("FieldSynopsis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WriteTime.
        /// </summary>
        public static string FieldWriteTime {
            get {
                return ResourceManager.GetString("FieldWriteTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Book&apos;s ISBN is lesser than X....
        /// </summary>
        public static string Filter_ISBN_N {
            get {
                return ResourceManager.GetString("Filter_ISBN_N", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Book&apos;s ISBN is more than X....
        /// </summary>
        public static string Filter_ISBN_P {
            get {
                return ResourceManager.GetString("Filter_ISBN_P", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Filter.
        /// </summary>
        public static string Filter_NoFilter {
            get {
                return ResourceManager.GetString("Filter_NoFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filter.
        /// </summary>
        public static string Filter_Title {
            get {
                return ResourceManager.GetString("Filter_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Book has X words....
        /// </summary>
        public static string Filter_Words {
            get {
                return ResourceManager.GetString("Filter_Words", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Check your Input - It is not a valid number.
        /// </summary>
        public static string Filter_WrongInput {
            get {
                return ResourceManager.GetString("Filter_WrongInput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Book written earlier than X....
        /// </summary>
        public static string Filter_WT_N {
            get {
                return ResourceManager.GetString("Filter_WT_N", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Book written later than X....
        /// </summary>
        public static string Filter_WT_P {
            get {
                return ResourceManager.GetString("Filter_WT_P", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filter: .
        /// </summary>
        public static string FilterLabel {
            get {
                return ResourceManager.GetString("FilterLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Book Name has.
        /// </summary>
        public static string FilterLabelWordsX1 {
            get {
                return ResourceManager.GetString("FilterLabelWordsX1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to words.
        /// </summary>
        public static string FilterLabelWordsX2 {
            get {
                return ResourceManager.GetString("FilterLabelWordsX2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fields Search.
        /// </summary>
        public static string FS_Title {
            get {
                return ResourceManager.GetString("FS_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to What to Search?.
        /// </summary>
        public static string FS_WhatToSearch {
            get {
                return ResourceManager.GetString("FS_WhatToSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You didn&apos;t specify what to search.
        /// </summary>
        public static string FS_WrongInput {
            get {
                return ResourceManager.GetString("FS_WrongInput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Keywords:.
        /// </summary>
        public static string KeywordsHover {
            get {
                return ResourceManager.GetString("KeywordsHover", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insert keywords, separating them with &apos;;&apos; symbol.
        /// </summary>
        public static string KS_Desc {
            get {
                return ResourceManager.GetString("KS_Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Keywords Search.
        /// </summary>
        public static string KS_Title {
            get {
                return ResourceManager.GetString("KS_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About Program.
        /// </summary>
        public static string MenuButtonAbout {
            get {
                return ResourceManager.GetString("MenuButtonAbout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Book.
        /// </summary>
        public static string MenuButtonAdd {
            get {
                return ResourceManager.GetString("MenuButtonAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fields Search.
        /// </summary>
        public static string MenuButtonFieldsSearch {
            get {
                return ResourceManager.GetString("MenuButtonFieldsSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filter.
        /// </summary>
        public static string MenuButtonFilter {
            get {
                return ResourceManager.GetString("MenuButtonFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear Filter.
        /// </summary>
        public static string MenuButtonFilterStop {
            get {
                return ResourceManager.GetString("MenuButtonFilterStop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Keywords Search.
        /// </summary>
        public static string MenuButtonKeywordsSearch {
            get {
                return ResourceManager.GetString("MenuButtonKeywordsSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mail Developer.
        /// </summary>
        public static string MenuButtonMail {
            get {
                return ResourceManager.GetString("MenuButtonMail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refresh Catalogue.
        /// </summary>
        public static string MenuButtonRefresh {
            get {
                return ResourceManager.GetString("MenuButtonRefresh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove Book.
        /// </summary>
        public static string MenuButtonRemove {
            get {
                return ResourceManager.GetString("MenuButtonRemove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear Search.
        /// </summary>
        public static string MenuButtonSearchStop {
            get {
                return ResourceManager.GetString("MenuButtonSearchStop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change Server.
        /// </summary>
        public static string MenuButtonServer {
            get {
                return ResourceManager.GetString("MenuButtonServer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Skins.
        /// </summary>
        public static string MenuButtonSkins {
            get {
                return ResourceManager.GetString("MenuButtonSkins", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CATALOGUE.
        /// </summary>
        public static string MenuTabCatalogue {
            get {
                return ResourceManager.GetString("MenuTabCatalogue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MISC.
        /// </summary>
        public static string MenuTabMisc {
            get {
                return ResourceManager.GetString("MenuTabMisc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SEARCH / FILTER.
        /// </summary>
        public static string MenuTabSearch {
            get {
                return ResourceManager.GetString("MenuTabSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not reach server. Please check your connection or server status..
        /// </summary>
        public static string NoConnection {
            get {
                return ResourceManager.GetString("NoConnection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete this book: &quot;.
        /// </summary>
        public static string RemoveConfirm {
            get {
                return ResourceManager.GetString("RemoveConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove Confirmation.
        /// </summary>
        public static string RemoveConfirmTitle {
            get {
                return ResourceManager.GetString("RemoveConfirmTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You didn&apos;t select a book to Remove.
        /// </summary>
        public static string RemoveNoSelect {
            get {
                return ResourceManager.GetString("RemoveNoSelect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Keywords (Hover To View).
        /// </summary>
        public static string SearchKW {
            get {
                return ResourceManager.GetString("SearchKW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search: .
        /// </summary>
        public static string SearchLabel {
            get {
                return ResourceManager.GetString("SearchLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to includes.
        /// </summary>
        public static string SearchLabelInc {
            get {
                return ResourceManager.GetString("SearchLabelInc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default.
        /// </summary>
        public static string SkinDefault {
            get {
                return ResourceManager.GetString("SkinDefault", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Magic.
        /// </summary>
        public static string SkinMagic {
            get {
                return ResourceManager.GetString("SkinMagic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Descending.
        /// </summary>
        public static string Sort_Down {
            get {
                return ResourceManager.GetString("Sort_Down", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ascending.
        /// </summary>
        public static string Sort_Up {
            get {
                return ResourceManager.GetString("Sort_Up", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sort: .
        /// </summary>
        public static string SortLabel {
            get {
                return ResourceManager.GetString("SortLabel", resourceCulture);
            }
        }
    }
}
